### ISSUE TITLE
Question on performance impact

### ISSUE THREAD

**Issue by micr0be** [ukncsc/zero-trust-architecture#10]
"each connection to a service should be authenticated, authorised against a policy, and encrypted"

How would this scale with regards to performance impact on a network?
Is that additional overhead worth a mention for larger scale networks and services?

**Comment by phlash** [comment]
In an implementation I have been helping architect, we chose to decentralise / cache both authorisation and access policies through caching of OpenIDConnect metadata with appropriate timeouts that limited the risk while providing the scalability and single failure tolerance we need. In other implementations I'm aware of, the design uses a distributed memory database (Redis) to hold the metadata required, this is more complex and less scaleable, but the was required as the transaction rate is much higher and consequent risk occurs faster. There is always going to be some impact on performance / scalability for security controls that need balancing against the residual risk of not having the controls, which needs a good threat model / risk assessment.

**Comment by micr0be** [comment]
very interesting, will keep that in mind.

Thanks for the reply
