### ISSUE TITLE
Grammar in #5 Device Health

### ISSUE THREAD

**Issue by bernie-p** [ukncsc/zero-trust-architecture#13]
The word "are" seems to be redundant in:

Attestation is a way of achieving this, taking a snapshot of the state of a device with claims about different components of the hardware and operating system are reported to the signal database for analysis.

**Comment by stu-h** [comment]
I've run it past a few people and amended it to:

Attestation is a way of achieving this, taking a snapshot of the state of a device with claims about different components of the hardware and operating system, that are reported to the signal database for analysis.
