### ISSUE TITLE
Need strong identities for software entities - not just human users and physical devices.

### ISSUE THREAD

**Issue by clymbon** [ukncsc/zero-trust-architecture#17]
Section 2 describes creating strong identities for "users", and Section 3 describes creating strong identities for "devices".  I take that to mean "human users" and "physical devices".  But that's not enough.  Section 4 says "Requests between services also need to be authenticated."  So that implies we need strong identities for "services".   Should services be treated like users, or somehow mapped to the users that "own" them?  Should they be treated like devices, or equated to the physical devices upon which they are running (probably not possible with a modern IaaS approach)?  

Or do they belong in a class of their own?  I think this is the case, but very little thought has been given to defining or describing what this means.

Imagine a microservices architecture for a control system.  User interfaces are provided in the form of dedicated "control panels", and access control for human users is provided primarily by controlling physical access to those control panels.  (If the reactor is melting down, you don't require a user to log in before you let her shut it down.)   Behind the user interfaces we might be trying to evolve to a service mesh architecture, with microservices invoking other microservices.  In current architectures, the software components that implement these microservices probably do implicitly trust other components that are on the network.  If we want to get away from this (and I agree we should) then we need to further develop the concept of strong identity for software processes.

**Comment by stu-h** [comment]
This is an excellent point - I think that we do need discuss how services are identified, do you think we could expand upon this in principle 4 or would a new principle be required?

I would have thought we'd create a dedicated identity of a service separate from a user or device, but as you say could be mapped to a user that is responsible for it, although I think this is out of scope of these principles.

**Comment by PeterR707** [comment]
Hi, Thank you for your comment and we have refreshed our guidance to reflect non human identities which can be found here  https://github.com/ukncsc/zero-trust-architecture/blob/master/02-Know-your-User-Service-and-Device-identities.md
