### ISSUE TITLE
Clarity around VPNs

### ISSUE THREAD

**Issue by thommck** [ukncsc/zero-trust-architecture#23]
I'm currently working on a zero trust strategy and glad to see it is lining up with the recommendations here :)
However, I'd really appreciate more clarity around VPNs as your statement contradicts the NCSC EUD guidance.
My opinion is that you don't need a VPN if all services are SaaS or use an HTTPS app proxy for internal LoB applications. The EUD guidance states that you should always push all traffic through a VPN. https://www.ncsc.gov.uk/collection/end-user-device-security/eud-overview/vpns. Unfortunately, some people I work with say this would put devices at risk if, say, they were using a public Wi-Fi hotspot, like in a coffee shop.
Therefore, can you expand on this in the zero trust guidance so we have a clear way forward? Thanks

**Comment by stu-h** [comment]
Hi @thommck,

Thanks for your comment, you're not alone :)

I'll working adding clarity around VPNs after I've received all feedback after the 31st Jan. In a nutshell my current thinking is if you have a well configured client, are accessing services that use good secure protocols, are doing proper monitoring on the host etc. you may be able to ditch the VPN. 

If transitioning from a traditional architecture, as a general rule turning off the VPN is the last thing you should do. That is, make sure you have all the benefits of a VPN addressed in your zero trust implementation before removing it. You may also find that some legacy applications need a VPN as trying to get them to work in a zero trust architecture would be risky or too much effort.

Hope this helps in the mean time check out the recently refreshed mobile device guidance, which references a zero trust architecture, here: https://www.ncsc.gov.uk/collection/mobile-device-guidance/infrastructure/network-architectures-for-remote-access

If you have any more thoughts on the matter do continue the conversation here.

**Comment by PeterR707** [comment]
Hi thank you for your comment we have added some clarity over VPNs on our main introduction page https://github.com/ukncsc/zero-trust-architecture/blob/master/README.md but also have at look at our updated VPN guidance that has some clarity over traffic outside of a VPN call a  'managed tunnel' https://www.ncsc.gov.uk/collection/mobile-device-guidance/virtual-private-networks
