### ISSUE TITLE
Traffic Inspection ?

### ISSUE THREAD

**Issue by absvyas** [ukncsc/zero-trust-architecture#24]
Given that zero trust, does not trust the network - does the monitoring section require an update to include inspection of authenticated and encrypted traffic?

If the device has been compromised, or has rogue software installed on it (perhaps a third party library as part of a COTS app) , it is not making authenticated and encrypted calls over a network.

I would welcome an update to include that traffic is inspected and evaluated against network policy prior to it being allowed to travel further. This may be easier for internal networks, however on external, would expect the use of something like GCP IAP or similar

Other options include monitoring the TLS handshake, or using mTLS to verify the identity of the caller, which can be used as additional telemetry with the device health.

**Comment by PeterR707** [comment]
Hi, Thank you for your comment and this is something we see as an issue as well. We have updated don't trust your own network principle  to reflect your comment above. 
https://github.com/ukncsc/zero-trust-architecture/blob/master/07-Don't-trust-any-network-including-your-own.md
