### ISSUE TITLE
Principle 6 - Network Monitoring

### ISSUE THREAD

**Issue by ColinRobbins** [ukncsc/zero-trust-architecture#49]
Should this section also reference cloud services, and the type of monitoring recommended?

I think this particularly important, as the comment:

> Further advice and guidance can be found with in the [NCSC Logging and protective monitoring page.](https://www.ncsc.gov.uk/collection/mobile-device-guidance/logging-and-protective-monitoring)

Links to a page that is on-premise oriented.

**Comment by PeterR707** [comment]
Hi Coin

Thanks again for the feedback, yes this is something to think about as the approach will be different. I will see if we have some guidance in this areas to link and call there is a different approach.

**Comment by stu-h** [comment]
I believe this is fixed in v1.0 as it links to the user audit section in the Cloud Security Principles
