### ISSUE TITLE
Opinion on "Focus your monitoring on devices and services"

### ISSUE THREAD

**Issue by ttinkr** [ukncsc/zero-trust-architecture#5]
Thank you for the good write-up of Zero Trust! I think it's a good starting point. 
In my opinion (tell me when I'm wrong) Zero Trust does not mean everthing is in the Cloud and everybody works over public WIFIs etc. It can also be that this is a kind of security overlay over a traditional network design. If you already have a network running you probably will not remove your Firewalls because you go all Zero Trust, right? :) I heard this when all the "Firewall is dead" talk came out, but I dont think this is really true.

So I would argue that your assumption here is kind of blurry:
> Given that devices and services are more exposed to network attack than in traditional architectures it’s important that comprehensive monitoring is carried out.

This assumption is based on a specific kind of implementation of Zero Trust, but is not true for all Zero Trust environments imho. 

I am happy discussing this with you and maybe learning that I misunderstood something and I'm wrong. Thanks for the work you put in!

**Comment by stu-h** [comment]
Great comment.

It's quite difficult to write for all scenarios but I think what you describe should be highlighted. I'll change that specific sentence you quoted, expanding it to other types of architectures.

I focused on the cloud angle as that's what most people are aiming for but I do work with a lot of people with large on-premise estates too. I also think the "security overlay" could apply to more modern architectures employing micro-segmentation or in the cloud, like when using Kubernetes.

I definitely wouldn't say remove all your firewalls etc. they are part of your layered defences, I guess what I'm trying to say is don't rely on them anymore. Does that make sense?

**Comment by grumpygolb** [comment]
Makes totally sense, thanks!

**Comment by PeterR707** [comment]
Hi Thank you for your comment - We have tried to cover you point under https://github.com/ukncsc/zero-trust-architecture/blob/master/07-Don't-trust-any-network-including-your-own.md were we state maintaining cyber hygiene on the network is still important.
