### ISSUE TITLE
Principle 7. Don't trust any network, including your own

### ISSUE THREAD

**Issue by ColinRobbins** [ukncsc/zero-trust-architecture#50]
Should this link to the cloud security principles?

Not all services run will be your own - this is brought out in Principle 8 "Choose services designed for zero trust".
So what if I choose a cloud service "designed for zero trust", as many are now being marketed.  
By linking to the cloud security principles, it makes it clear you need to verify the CSP in order to be able to trust their "Zero Trust" claims.

**Comment by PeterR707** [comment]
Hi Colin
Thank you for the comment 
Yes we totally agree, we should link out to our cloud guidance for this section, as you quite rightly say  you need verify the service provider as part of the process of having trust in their ZT implementation. I will add a link into the document and let you know when its complete.

**Comment by stu-h** [comment]
Fixed in v1.0
