### ISSUE TITLE
Principles 2 & 3

### ISSUE THREAD

**Issue by ColinH1** [ukncsc/zero-trust-architecture#51]
General comment on Principles 2 & 3.

To maintain that zero trust model at an operational levels there any thoughts to include guidance on maintaining assets.  To really follow the Principles of 2. Know your User, Service and Device identities and 3. Know the health of your users, devices and services.  The asset inventory management of especially of services and devices needs to be very good otherwise your zero trust architecture starts to break.

Regards
Colin

**Comment by PeterR707** [comment]
Hi Colin
Thank you for your comment and we totally agree this does underpin both theses ZT principles. This is something we are working on internally "what does a good asset management system look like". This will feed into our next iteration of guidance, once its updated I will let you know so you can have a look. It would be good to know what you think.

**Comment by ColinH1** [comment]
Thank Peter, look forward to seeing the guidance.  As I am sure you know good asset management is big challenge for most organisations.  It is a serious subject that needs to be addressed and a lot of the other principles in ZT have some dependency on it.  that being said its a journey you have start to work towards otherwise it creates so much unknown risk.

**Comment by stu-h** [comment]
I believe this is covered in principle 1 of the v1.0 release
