### ISSUE TITLE
Rubik's Cube Suggestion to reduce Number of Principles

### ISSUE THREAD

**Issue by Phil-NZ** [ukncsc/zero-trust-architecture#63]
I had a little trouble absorbing all the active words in each of the Principles; and came to the simplistic conclusion that the first 3 all have a common baseline/context.  That being the case, did you consider re-shaping the first 3 principles along lines of the following:
1 - know your users, services and devices:
     a.  Architecture
     b.  Identities 
     c.  Health

I know it is cheating, if you said you'd reduced the Number of Principles down to 6; as this one would have 3 sub-parts to it!

For a simple person like myself, or a typical Enterprise Architect, the above reads easier and clearly identifies to target components (architecture, identities and health).

**Comment by stu-h** [comment]
Hi Phil, 
 
At this time I'll be keeping the current numbering scheme as it is. This is to enable the various stakeholders to reference the specific principles directly and to keep each section reasonably short in length.

Thanks for taking the time to feedback and please do continue.

Many thanks,
Stuart
