### ISSUE TITLE
Don't Trust Any Content

### ISSUE THREAD

**Issue by ColinRobbins** [ukncsc/zero-trust-architecture#77]
I am not sure if you are still taking comments, but here goes...

Principle 7 says "Don't trust any network between the device and the service it's accessing, this includes the local network".
Inline with other NCSC principles, scuh as the secure communication principles, and cross domain principles, should this be extended to include: "Don't trust any content shared between networks"?

**Comment by stu-h** [comment]
Hi Colin,

We review comments periodically and I'm just writing to acknowledge your comment.

We'll consider incorporating this if we refresh the guidance in the future. 

Thanks,
Stu
