### ISSUE TITLE
What license is this work released under?

### ISSUE THREAD

**Issue by kurtseifried** [ukncsc/zero-trust-architecture#78]
We couldn’t find any code matching 'license' in [ukncsc/zero-trust-architecture](https://github.com/ukncsc/zero-trust-architecture)

I assume it is under Crown copyright, but is it OGL licensed or something else?

**Comment by cronky** [comment]
Looks like most of the other UKNCSC repositories are Licensed as Apache-2.0

**Comment by cronky** [comment]
Given its not stated and the content is also on their website I'd say the terms that are outlined here would apply: https://www.ncsc.gov.uk/section/about-this-website/terms-and-conditions#section_2

**Comment by stu-h** [comment]
Hi @kurtseifried, thanks for your question. You are correct that it is Crown Copyright and I think we intended it to use the OGLv3 given that's usually our default for documentation. It looks like we didn't explicitly set a licence when we set up the repo, I will update the repo to add the OGL.

**Comment by kurtseifried** [comment]
> Hi @kurtseifried, thanks for your question. You are correct that it is Crown Copyright and I think we intended it to use the OGLv3 given that's usually our default for documentation. It looks like we didn't explicitly set a licence when we set up the repo, I will update the repo to add the OGL.

Thanks, this helps.
